# fly.toml app configuration file generated for simple-budget on 2023-10-22T14:35:25+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "simple-budget"
primary_region = "waw"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
  PORT = "8080"
